Custom field layout
TeraViks/ACDC_2024 pull request #60
Opened 2024-03-07 02:32 UTC by jasone

2024-03-09 20:47 UTC, SamueljWilson commented on src/main/java/frc/robot/Constants.java
> +    kAprilTagFieldLayout.getTags().get(7).pose;
Should be 6 not 7

2024-03-09 20:48 UTC, SamueljWilson requested changes

2024-03-09 20:48 UTC, SamueljWilson commented on src/main/java/frc/robot/Constants.java
> +      kAprilTagFieldLayout.getTags().get(4).pose;
Same as above

2024-03-09 20:48 UTC, SamueljWilson commented on src/main/java/frc/robot/Constants.java
> +    kAprilTagFieldLayout.getTags().get(7).pose;
Should be 6 not 7

2024-03-09 20:51 UTC, SamueljWilson approved these changes

2024-03-09 21:52 UTC, jasone commented on src/main/java/frc/robot/Constants.java
> +      kAprilTagFieldLayout.getTags().get(4).pose;
Addressed in the context of #59.

2024-03-09 21:52 UTC, jasone commented on src/main/java/frc/robot/Constants.java
> +    kAprilTagFieldLayout.getTags().get(7).pose;
Addressed in the context of #59.

2024-03-10 01:00 UTC, SamueljWilson approved these changes

2024-03-10 01:45 UTC, merged